# Generated by Django 2.1.5 on 2019-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0002_auto_20190217_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msch',
            name='intv_dt',
            field=models.DateField(blank=True, null=True, verbose_name='면접일'),
        ),
    ]
