# Generated by Django 2.1.5 on 2019-02-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0003_auto_20190217_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msch',
            name='img_src',
        ),
    ]
