# Generated by Django 2.1.5 on 2019-02-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0005_msch_img_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msch',
            name='img_src',
        ),
    ]
