# Generated by Django 2.1.5 on 2019-02-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0006_remove_msch_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='msch',
            name='img_src',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소개 사진'),
        ),
    ]
