# Generated by Django 2.1.5 on 2019-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0008_cm_apl_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='cm_surv',
            fields=[
                ('ques_no', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='만족도 조사 항목 ID')),
                ('ansr_div', models.CharField(max_length=1, verbose_name='응답자 구분(CM0001)')),
                ('ques_type', models.CharField(max_length=1, verbose_name='질문유형(CM0002)')),
                ('ques_div', models.CharField(max_length=1, verbose_name='질문구분(CM0003)')),
                ('ques_desc', models.CharField(max_length=500, verbose_name='질문지')),
                ('use_yn', models.CharField(default='Y', max_length=1, verbose_name='사용여부(CM0005)')),
                ('sort_seq', models.PositiveIntegerField(blank=True, null=True, verbose_name='정렬 순서')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
