# Generated by Django 2.1.5 on 2019-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0010_cm_surv_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='cm_surv_q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surv_id', models.PositiveIntegerField(verbose_name='문항세트 ID')),
                ('ques_no', models.PositiveIntegerField(verbose_name='만족도 조사 항목 ID')),
                ('sort_seq', models.PositiveIntegerField(verbose_name='정렬 순서')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
