# Generated by Django 2.1.5 on 2019-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0011_cm_surv_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='cm_surv_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgm_id', models.CharField(max_length=10, verbose_name='만족도 조사 대상(멘토스쿨, 프로그램, 학습외)')),
                ('surv_seq', models.CharField(max_length=2, verbose_name='대상 내 유형')),
                ('ansr_id', models.CharField(max_length=10, verbose_name='응답자 ID')),
                ('ques_no', models.PositiveIntegerField(verbose_name='만족도 조사 항목 ID')),
                ('ansr_div', models.CharField(max_length=1, verbose_name='응답자 구분(CM0001)')),
                ('ans_t1', models.PositiveIntegerField(blank=True, null=True, verbose_name='선다형 답')),
                ('ans_t2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='수필형 답')),
                ('ans_t3', models.CharField(blank=True, max_length=2, null=True, verbose_name='선택 답')),
                ('ques_dt', models.CharField(max_length=8, verbose_name='설문조사일자')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
