# Generated by Django 2.1.5 on 2019-02-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0013_auto_20190217_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='cm_sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_menu_id', models.CharField(max_length=8, verbose_name='사용 프로그램 ID')),
                ('seq', models.PositiveIntegerField(verbose_name='순번')),
                ('msg_gbn_nm', models.CharField(blank=True, max_length=100, null=True, verbose_name='메세지구분명')),
                ('msg_ttl', models.CharField(blank=True, max_length=100, null=True, verbose_name='메세지제목')),
                ('msg_ctnt', models.CharField(blank=True, max_length=2000, null=True, verbose_name='메세지내용')),
                ('reply_telno', models.CharField(blank=True, max_length=20, null=True, verbose_name='회신번호')),
                ('msg_fg', models.CharField(blank=True, max_length=1, null=True, verbose_name='메세지구분{E0610}')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
