# Generated by Django 2.1.5 on 2019-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0015_mp_plnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp_mte',
            name='grd_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='보호자 연락처'),
        ),
        migrations.AlterField(
            model_name='mp_mte',
            name='mob_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='휴대전화'),
        ),
        migrations.AlterField(
            model_name='mp_mte',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='상태(MP0054)'),
        ),
        migrations.AlterField(
            model_name='mp_mte',
            name='tchr_tel',
            field=models.CharField(max_length=20, verbose_name='지도교사 전화번호'),
        ),
    ]
