# Generated by Django 2.1.5 on 2019-02-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0019_mentee_yr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mentee',
        ),
    ]
