# Generated by Django 2.1.5 on 2019-02-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0021_mentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='mp_plnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.CharField(max_length=10, verbose_name='멘토링 프로그램ID')),
                ('apl_no', models.PositiveIntegerField(verbose_name='멘토 지원 NO')),
                ('pln_no', models.PositiveIntegerField(verbose_name='계획 주차')),
                ('pln_sdt', models.DateField(blank=True, null=True, verbose_name='주 교육시작일(일)')),
                ('pln_edt', models.DateField(blank=True, null=True, verbose_name='주 교육종료일(토)')),
                ('mtr_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='멘토링 내용')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
