# Generated by Django 2.1.5 on 2019-02-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0022_mp_plnd'),
    ]

    operations = [
        migrations.CreateModel(
            name='mp_att',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.CharField(max_length=10, verbose_name='멘토링 프로그램ID')),
                ('apl_no', models.PositiveIntegerField(verbose_name='멘토 지원 NO')),
                ('att_no', models.PositiveIntegerField(verbose_name='출석순서(SEQ)')),
                ('mp_div', models.CharField(max_length=1, verbose_name='교육구분(MP0059)')),
                ('spc_no', models.PositiveIntegerField(verbose_name='학습외 프로그램NO')),
                ('att_div', models.CharField(max_length=1, verbose_name='출석구븐(MP0063)')),
                ('att_sts', models.CharField(max_length=1, verbose_name='출석 상태(MP0060)')),
                ('att_sdt', models.DateTimeField(blank=True, null=True, verbose_name='출석일시(교육시작일시)')),
                ('att_saddr', models.CharField(blank=True, max_length=200, null=True, verbose_name='멘토링 시작주소')),
                ('att_sdist', models.PositiveIntegerField(blank=True, null=True, verbose_name='멘토링 주소 거리(m)')),
                ('att_edt', models.DateTimeField(blank=True, null=True, verbose_name='교육종료일시')),
                ('att_eaddr', models.CharField(blank=True, max_length=200, null=True, verbose_name='멘토링 종료주소')),
                ('att_edist', models.PositiveIntegerField(blank=True, null=True, verbose_name='멘토링 주소 거리(m)')),
                ('elap_tm', models.TimeField(blank=True, null=True, verbose_name='경과시간')),
                ('appr_tm', models.PositiveIntegerField(blank=True, null=True, verbose_name='인정시간')),
                ('mtr_desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='멘토링 내용(보고서)')),
                ('mtr_pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='멘토링 사진(url)')),
                ('appr_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='승인자ID')),
                ('appr_nm', models.CharField(blank=True, max_length=20, null=True, verbose_name='승인자명')),
                ('appr_dt', models.DateTimeField(blank=True, null=True, verbose_name='보호자 승인일시')),
                ('mgr_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='관리자ID')),
                ('mgr_dt', models.DateTimeField(blank=True, null=True, verbose_name='관리자 승인일시')),
                ('expl_yn', models.CharField(blank=True, max_length=1, null=True, verbose_name='소명상태')),
                ('rep_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='보고서 NO')),
                ('exp_div', models.CharField(blank=True, max_length=1, null=True, verbose_name='활동비 지급여부(MP0061)')),
                ('exp_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='활동비 지급 NO')),
                ('exp_dt', models.DateTimeField(blank=True, null=True, verbose_name='활동비 지급일')),
                ('exp_amt', models.PositiveIntegerField(blank=True, null=True, verbose_name='지급 활동비')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
