# Generated by Django 2.1.5 on 2019-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0023_mp_att'),
    ]

    operations = [
        migrations.CreateModel(
            name='mp_att_mte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.CharField(max_length=10, verbose_name='멘토링 프로그램ID')),
                ('mnte_no', models.PositiveIntegerField(verbose_name='멘티 지원 NO')),
                ('apl_no', models.PositiveIntegerField(verbose_name='멘토 지원 NO')),
                ('att_no', models.PositiveIntegerField(verbose_name='출석순서(SEQ)')),
                ('att_div', models.CharField(max_length=1, verbose_name='출석구분(MP0063)')),
                ('att_sdt', models.DateTimeField(blank=True, null=True, verbose_name='교육시작일시')),
                ('att_edt', models.DateTimeField(blank=True, null=True, verbose_name='교육종료일시')),
                ('elap_tm', models.TimeField(blank=True, null=True, verbose_name='경과시간')),
                ('appr_tm', models.PositiveIntegerField(blank=True, null=True, verbose_name='인정시간')),
                ('mtr_thght', models.CharField(blank=True, max_length=200, null=True, verbose_name='멘토링 소감')),
                ('appr_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='승인자ID')),
                ('appr_nm', models.CharField(blank=True, max_length=20, null=True, verbose_name='승인자명')),
                ('appr_dt', models.DateTimeField(blank=True, null=True, verbose_name='보호자 승인일시')),
                ('mgr_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='관리자ID')),
                ('mgr_dt', models.DateTimeField(blank=True, null=True, verbose_name='관리자 승인일시')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
