# Generated by Django 2.1.5 on 2019-02-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0024_mp_att_mte'),
    ]

    operations = [
        migrations.CreateModel(
            name='mp_rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.CharField(max_length=10, verbose_name='멘토링 프로그램ID')),
                ('apl_no', models.PositiveIntegerField(verbose_name='멘토 지원 NO')),
                ('rep_no', models.PositiveIntegerField(verbose_name='보고서 NO')),
                ('rep_div', models.CharField(max_length=1, verbose_name='보고서 구분(MP0062)')),
                ('rep_ttl', models.CharField(blank=True, max_length=200, null=True, verbose_name='보고서 제목')),
                ('mtr_obj', models.CharField(blank=True, max_length=1000, null=True, verbose_name='학습목표')),
                ('rep_dt', models.DateTimeField(blank=True, null=True, verbose_name='보고서작성일')),
                ('req_dt', models.DateTimeField(blank=True, null=True, verbose_name='승인요청일')),
                ('mtr_desc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='학습내용')),
                ('coatching', models.CharField(blank=True, max_length=1000, null=True, verbose_name='학습외 지도(상담)')),
                ('spcl_note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='특이사항')),
                ('mtr_revw', models.CharField(blank=True, max_length=1000, null=True, verbose_name='소감문')),
                ('appr_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='승인자ID')),
                ('appr_nm', models.CharField(blank=True, max_length=20, null=True, verbose_name='승인자명')),
                ('appr_dt', models.DateTimeField(blank=True, null=True, verbose_name='보호자 승인일시')),
                ('mgr_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='관리자ID')),
                ('mgr_dt', models.DateTimeField(blank=True, null=True, verbose_name='관리자 승인일시')),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='상태(MP0070)')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
