# Generated by Django 2.1.5 on 2019-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0026_mp_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp_rep',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='상태(MP0070)'),
        ),
    ]
