# Generated by Django 2.1.5 on 2019-02-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0028_auto_20190217_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ms_mrk',
            options={},
        ),
        migrations.AddField(
            model_name='ms_mrk',
            name='item_cd',
            field=models.Field(blank=True, null=True, verbose_name='채점항목코드-SEQ별'),
        ),
        migrations.AddField(
            model_name='ms_mrk',
            name='item_nm',
            field=models.Field(blank=True, null=True, verbose_name='채점항목명'),
        ),
        migrations.AlterUniqueTogether(
            name='ms_mrk',
            unique_together=set(),
        ),
    ]
