# Generated by Django 2.1.5 on 2019-02-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0029_auto_20190217_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mp_mrk',
        ),
    ]
