# Generated by Django 2.1.5 on 2019-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0030_delete_mp_mrk'),
    ]

    operations = [
        migrations.CreateModel(
            name='mp_mrk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_id', models.CharField(max_length=10, verbose_name='멘토링프로그램ID')),
                ('test_div', models.CharField(max_length=10, verbose_name='전형구분(서류/면접)MP0039')),
                ('apl_no', models.CharField(max_length=10, verbose_name='지원 NO')),
                ('mrk_seq', models.PositiveIntegerField(verbose_name='채점 항목 SEQ(NO)')),
                ('mrk_no', models.PositiveIntegerField(verbose_name='채점자 NO')),
                ('mrk_id', models.CharField(max_length=10, verbose_name='채점자 ID')),
                ('mak_nm', models.CharField(max_length=20, verbose_name='채점자 명')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='점수')),
                ('item_cd', models.Field(blank=True, null=True, verbose_name='채점항목코드-SEQ별')),
                ('item_nm', models.Field(blank=True, null=True, verbose_name='채점항목명')),
                ('ins_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID')),
                ('ins_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP')),
                ('ins_dt', models.DateTimeField(blank=True, null=True, verbose_name='입력일시')),
                ('ins_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID')),
                ('upd_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID')),
                ('upd_ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP')),
                ('upd_dt', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('upd_pgm', models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID')),
            ],
        ),
    ]
