# Generated by Django 2.1.5 on 2019-02-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0038_auto_20190217_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp_mrk',
            name='item_cd',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='채점항목코드-SEQ별'),
        ),
        migrations.AlterField(
            model_name='mp_mrk',
            name='item_nm',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='채점항목명'),
        ),
    ]
