# Generated by Django 2.1.5 on 2019-02-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0041_mp_mrk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mp_mrk',
        ),
    ]
