# Generated by Django 2.1.5 on 2019-02-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0045_ms_mrk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_mrk',
            options={'verbose_name': '멘토링 프로그램 지원서 채점', 'verbose_name_plural': '멘토링 프로그램 지원서 채점'},
        ),
    ]
