# Generated by Django 2.1.5 on 2019-02-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0046_auto_20190217_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mp_mrk',
            unique_together={('mp_id', 'test_div', 'apl_no', 'mrk_seq', 'mrk_no')},
        ),
    ]
