# Generated by Django 2.1.5 on 2019-02-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0049_auto_20190217_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_spc',
            options={'verbose_name': '학습외 프로그램', 'verbose_name_plural': '학습외 프로그램'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_spc',
            unique_together={('mp_id', 'spc_no')},
        ),
    ]
