# Generated by Django 2.1.5 on 2019-02-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0050_auto_20190217_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_spc_sub',
            options={'verbose_name': '학습외 프로그램 속성', 'verbose_name_plural': '학습외 프로그램 속성'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_spc_sub',
            unique_together={('mp_id', 'spc_no', 'att_id', 'att_seq')},
        ),
    ]
