# Generated by Django 2.1.5 on 2019-02-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0051_auto_20190217_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_spc_mtr',
            options={'verbose_name': '학습외 프로그램 참여 멘토', 'verbose_name_plural': '학습외 프로그램 참여 멘토'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_spc_mtr',
            unique_together={('mp_id', 'apl_no', 'spc_no', 'spc_apl_no')},
        ),
    ]
