# Generated by Django 2.1.5 on 2019-02-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0052_auto_20190217_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_spc_mte',
            options={'verbose_name': '학습외 프로그램 참여 멘티', 'verbose_name_plural': '학습외 프로그램 참여 멘티'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_spc_mte',
            unique_together={('mp_id', 'mnte_no')},
        ),
    ]
