# Generated by Django 2.1.5 on 2019-02-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0054_auto_20190217_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msch',
            options={'verbose_name': '개설멘토스쿨', 'verbose_name_plural': '개설멘토스쿨'},
        ),
    ]
