# Generated by Django 2.1.5 on 2019-02-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0057_auto_20190217_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mp_mte',
        ),
    ]
