# Generated by Django 2.1.5 on 2019-02-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0059_auto_20190217_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_mte_log',
            options={'verbose_name': '프로그램 지원자(멘티) 로그', 'verbose_name_plural': '프로그램 지원자(멘티) 로그'},
        ),
        migrations.AlterIndexTogether(
            name='mp_mte_log',
            index_together={('mnte_id', 'mp_id')},
        ),
    ]
