# Generated by Django 2.1.5 on 2019-02-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0060_auto_20190217_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm_apl_q',
            options={'verbose_name': '지원서 질문', 'verbose_name_plural': '지원서 질문'},
        ),
    ]
