# Generated by Django 2.1.5 on 2019-02-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0061_auto_20190217_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm_surv',
            options={'verbose_name': '만족도 조사 문항', 'verbose_name_plural': '만족도 조사 문항'},
        ),
    ]
