# Generated by Django 2.1.5 on 2019-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0062_auto_20190217_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm_surv_q',
            options={'verbose_name': '만족도 조사 출제 문항', 'verbose_name_plural': '만족도 조사 출제 문항'},
        ),
        migrations.AlterModelOptions(
            name='cm_surv_t',
            options={'verbose_name': '만족도 조사 출제 세트', 'verbose_name_plural': '만족도 조사 출제 세트'},
        ),
        migrations.AlterUniqueTogether(
            name='cm_surv_q',
            unique_together={('surv_id', 'ques_no')},
        ),
    ]
