# Generated by Django 2.1.5 on 2019-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0063_auto_20190217_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm_surv_a',
            options={'verbose_name': '만족도 조사 답변', 'verbose_name_plural': '만족도 조사 답변'},
        ),
        migrations.AlterUniqueTogether(
            name='cm_surv_a',
            unique_together={('pgm_id', 'surv_seq', 'ansr_id', 'ques_no')},
        ),
    ]
