# Generated by Django 2.1.5 on 2019-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0065_auto_20190217_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cm_sms',
            options={'verbose_name': '문자메시지 형식', 'verbose_name_plural': '문자메시지 형식'},
        ),
        migrations.AlterUniqueTogether(
            name='cm_sms',
            unique_together={('sys_menu_id', 'seq')},
        ),
    ]
