# Generated by Django 2.1.5 on 2019-02-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0067_auto_20190217_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_plnd',
            options={'verbose_name': '프로그램 수행 계획서 상세', 'verbose_name_plural': '프로그램 수행 계획서 상세'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_plnd',
            unique_together={('mp_id', 'apl_no', 'pln_no')},
        ),
        migrations.AlterIndexTogether(
            name='mp_plnd',
            index_together={('apl_no',)},
        ),
    ]
