# Generated by Django 2.1.5 on 2019-02-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0068_auto_20190217_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_att',
            options={'verbose_name': '프로그램 출석부(멘토)', 'verbose_name_plural': '프로그램 출석부(멘토)'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_att',
            unique_together={('mp_id', 'apl_no', 'att_no')},
        ),
        migrations.AlterIndexTogether(
            name='mp_att',
            index_together={('apl_no',)},
        ),
    ]
