# Generated by Django 2.1.5 on 2019-02-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0069_auto_20190217_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_att_mte',
            options={'verbose_name': '프로그램 출석부(멘티)', 'verbose_name_plural': '프로그램 출석부(멘티)'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_att_mte',
            unique_together={('mp_id', 'mnte_no', 'apl_no', 'att_no')},
        ),
        migrations.AlterIndexTogether(
            name='mp_att_mte',
            index_together={('mnte_no',)},
        ),
    ]
