# Generated by Django 2.1.5 on 2019-02-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0070_auto_20190217_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_rep',
            options={'verbose_name': '프로그램 보고서', 'verbose_name_plural': '프로그램 보고서'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_rep',
            unique_together={('mp_id', 'apl_no', 'rep_no')},
        ),
        migrations.AlterIndexTogether(
            name='mp_rep',
            index_together={('apl_no',)},
        ),
    ]
