# Generated by Django 2.1.5 on 2019-02-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0073_auto_20190217_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_exp',
            options={'verbose_name': '프로그램 활동비', 'verbose_name_plural': '프로그램 활동비'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_exp',
            unique_together={('mp_id', 'apl_no', 'exp_no')},
        ),
        migrations.AlterIndexTogether(
            name='mp_exp',
            index_together={('apl_no',)},
        ),
    ]
