# Generated by Django 2.1.5 on 2019-02-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0074_auto_20190217_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ms_apl',
            options={'verbose_name': '멘토스쿨 지원자', 'verbose_name_plural': '멘토스쿨 지원자'},
        ),
        migrations.AlterUniqueTogether(
            name='ms_apl',
            unique_together={('ms_id', 'apl_no')},
        ),
        migrations.AlterIndexTogether(
            name='ms_apl',
            index_together={('apl_nm',)},
        ),
    ]
