# Generated by Django 2.1.5 on 2019-02-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0075_auto_20190217_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ms_mrk',
            options={'verbose_name': '지원서 채점', 'verbose_name_plural': '지원서 채점'},
        ),
        migrations.AlterUniqueTogether(
            name='ms_mrk',
            unique_together={('ms_id', 'test_div', 'apl_no', 'mrk_seq', 'mrk_no')},
        ),
    ]
