# Generated by Django 2.1.5 on 2019-02-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0077_auto_20190217_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentee',
            options={'verbose_name': '멘티', 'verbose_name_plural': '멘티'},
        ),
    ]
