# Generated by Django 2.1.5 on 2019-02-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0078_auto_20190217_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name': '학부모(보호자 Gardian)', 'verbose_name_plural': '학부모(보호자 Gardian)'},
        ),
    ]
