# Generated by Django 2.1.5 on 2019-02-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0079_auto_20190217_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '교사(학교)', 'verbose_name_plural': '교사(학교)'},
        ),
    ]
