# Generated by Django 2.1.5 on 2019-02-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0080_auto_20190217_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpgm',
            options={'verbose_name': '멘토링프로그램', 'verbose_name_plural': '멘토링프로그램'},
        ),
    ]
