# Generated by Django 2.1.5 on 2019-02-17 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0081_auto_20190217_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_sub',
            options={'verbose_name': '멘토링프로그램 속성', 'verbose_name_plural': '멘토링프로그램 속성'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_sub',
            unique_together={('ms_id', 'att_id', 'att_seq')},
        ),
    ]
