# Generated by Django 2.1.5 on 2019-02-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0082_auto_20190217_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mp_sub',
            old_name='ms_id',
            new_name='mp_id',
        ),
        migrations.AlterUniqueTogether(
            name='mp_sub',
            unique_together={('mp_id', 'att_id', 'att_seq')},
        ),
    ]
