# Generated by Django 2.1.5 on 2019-02-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0083_auto_20190217_2206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mp_sub',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='ins_dt',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='ins_id',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='ins_ip',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='ins_pgm',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='sort_seq',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='upd_dt',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='upd_id',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='upd_ip',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='upd_pgm',
        ),
        migrations.RemoveField(
            model_name='mp_sub',
            name='use_yn',
        ),
    ]
