# Generated by Django 2.1.5 on 2019-02-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0084_auto_20190217_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp_sub',
            name='ins_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입력일시'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='ins_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='입력자ID'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='ins_ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='입력자IP'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='ins_pgm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='입력프로그램ID'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='sort_seq',
            field=models.PositiveIntegerField(default=1, verbose_name='정렬'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='upd_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='upd_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='수정자ID'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='upd_ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='수정자IP'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='upd_pgm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='수정프로그램ID'),
        ),
        migrations.AddField(
            model_name='mp_sub',
            name='use_yn',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='사용여부'),
        ),
        migrations.AlterUniqueTogether(
            name='mp_sub',
            unique_together={('mp_id', 'att_id', 'att_seq')},
        ),
    ]
