# Generated by Django 2.1.5 on 2019-02-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0085_auto_20190217_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mp_sub',
        ),
    ]
