# Generated by Django 2.1.5 on 2019-02-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0091_auto_20190217_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_mtr',
            options={'verbose_name': '프로그램 지원자(멘토)', 'verbose_name_plural': '프로그램 지원자(멘토)'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_mtr',
            unique_together={('mp_id', 'apl_no')},
        ),
        migrations.AlterIndexTogether(
            name='mp_mtr',
            index_together={('mntr_id',)},
        ),
    ]
