# Generated by Django 2.1.5 on 2019-02-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0092_auto_20190217_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_mtr_log',
            options={'verbose_name': '프로그램 지원자(멘토) 로그', 'verbose_name_plural': '프로그램 지원자(멘토) 로그'},
        ),
        migrations.AlterIndexTogether(
            name='mp_mtr_log',
            index_together={('mntr_id', 'mp_id')},
        ),
    ]
