# Generated by Django 2.1.5 on 2019-02-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0093_auto_20190217_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_ans',
            options={'verbose_name': '멘토링 프로그램 지원서 답변', 'verbose_name_plural': '멘토링 프로그램 지원서 답변'},
        ),
        migrations.AlterUniqueTogether(
            name='mp_ans',
            unique_together={('mp_id', 'test_div', 'apl_no', 'ques_no')},
        ),
    ]
