# Generated by Django 2.1.5 on 2019-02-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0094_auto_20190217_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ms_sub',
        ),
    ]
