# Generated by Django 2.1.5 on 2019-02-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0096_auto_20190218_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ms_sub',
        ),
    ]
