# Generated by Django 2.1.5 on 2019-02-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service20', '0098_auto_20190218_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp_plnh',
            name='mtr_sub',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='지도과목'),
        ),
    ]
